# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if ::Employments::DisabilityType.count == 0
  ::Employments::DisabilityType.create!(name: "Física: miembros inferiores, miembros superiores")
  ::Employments::DisabilityType.create!(name: "Mental")
  ::Employments::DisabilityType.create!(name: "Intelectual")
  ::Employments::DisabilityType.create!(name: "Visual: baja visión, ceguera total")
  ::Employments::DisabilityType.create!(name: "Audición: hipoacusia, sordera total, deficiencia auditiva")
end

if ::Employments::DisabilityCertification.count == 0
  ::Employments::DisabilityCertification.create!(name: "[no poseo certificación]")
  ::Employments::DisabilityCertification.create!(name: "ISSS")
  ::Employments::DisabilityCertification.create!(name: "ISRI")
  ::Employments::DisabilityCertification.create!(name: "FOPROLYD")
  ::Employments::DisabilityCertification.create!(name: "IPSFA")
  ::Employments::DisabilityCertification.create!(name: "INPEP")
  ::Employments::DisabilityCertification.create!(name: "ISRI")
  ::Employments::DisabilityCertification.create!(name: "SSF")
end

if ::Employments::Country.count == 0
  ::Employments::Country.create!(name: "Akrotiri")
  ::Employments::Country.create!(name: "Albania")
  ::Employments::Country.create!(name: "Alemania")
  ::Employments::Country.create!(name: "Andorra")
  ::Employments::Country.create!(name: "Angola")
  ::Employments::Country.create!(name: "Anguila")
  ::Employments::Country.create!(name: "Antártida")
  ::Employments::Country.create!(name: "Antigua y Barbuda")
  ::Employments::Country.create!(name: "Antillas Neerlandesas")
  ::Employments::Country.create!(name: "Arabia Saudí")
  ::Employments::Country.create!(name: "Arctic Ocean")
  ::Employments::Country.create!(name: "Argelia")
  ::Employments::Country.create!(name: "Argentina")
  ::Employments::Country.create!(name: "Armenia")
  ::Employments::Country.create!(name: "Aruba")
  ::Employments::Country.create!(name: "Ashmore and Cartier Islands")
  ::Employments::Country.create!(name: "Atlantic Ocean")
  ::Employments::Country.create!(name: "Australia")
  ::Employments::Country.create!(name: "Austria")
  ::Employments::Country.create!(name: "Azerbaiyán")
  ::Employments::Country.create!(name: "Bahamas")
  ::Employments::Country.create!(name: "Bahráin")
  ::Employments::Country.create!(name: "Bangladesh")
  ::Employments::Country.create!(name: "Barbados")
  ::Employments::Country.create!(name: "Bélgica")
  ::Employments::Country.create!(name: "Belice")
  ::Employments::Country.create!(name: "Benín")
  ::Employments::Country.create!(name: "Bermudas")
  ::Employments::Country.create!(name: "Bielorrusia")
  ::Employments::Country.create!(name: "Birmania; Myanmar")
  ::Employments::Country.create!(name: "Bolivia")
  ::Employments::Country.create!(name: "Bosnia y Hercegovina")
  ::Employments::Country.create!(name: "Botsuana")
  ::Employments::Country.create!(name: "Brasil")
  ::Employments::Country.create!(name: "Brunéi")
  ::Employments::Country.create!(name: "Bulgaria")
  ::Employments::Country.create!(name: "Burkina Faso")
  ::Employments::Country.create!(name: "Burundi")
  ::Employments::Country.create!(name: "Bután")
  ::Employments::Country.create!(name: "Cabo Verde")
  ::Employments::Country.create!(name: "Camboya")
  ::Employments::Country.create!(name: "Camerún")
  ::Employments::Country.create!(name: "Canadá")
  ::Employments::Country.create!(name: "Chad")
  ::Employments::Country.create!(name: "Chile")
  ::Employments::Country.create!(name: "China")
  ::Employments::Country.create!(name: "Chipre")
  ::Employments::Country.create!(name: "Clipperton Island")
  ::Employments::Country.create!(name: "Colombia")
  ::Employments::Country.create!(name: "Comoras")
  ::Employments::Country.create!(name: "Congo")
  ::Employments::Country.create!(name: "Coral Sea Islands")
  ::Employments::Country.create!(name: "Corea del Norte")
  ::Employments::Country.create!(name: "Corea del Sur")
  ::Employments::Country.create!(name: "Costa de Marfil")
  ::Employments::Country.create!(name: "Costa Rica")
  ::Employments::Country.create!(name: "Croacia")
  ::Employments::Country.create!(name: "Cuba")
  ::Employments::Country.create!(name: "Dhekelia")
  ::Employments::Country.create!(name: "Dinamarca")
  ::Employments::Country.create!(name: "Dominica")
  ::Employments::Country.create!(name: "Ecuador")
  ::Employments::Country.create!(name: "Egipto")
  ::Employments::Country.create!(name: "El Salvador")
  ::Employments::Country.create!(name: "El Vaticano")
  ::Employments::Country.create!(name: "Emiratos &#193;rabes Unidos")
  ::Employments::Country.create!(name: "Eritrea")
  ::Employments::Country.create!(name: "Eslovaquia")
  ::Employments::Country.create!(name: "Eslovenia")
  ::Employments::Country.create!(name: "España")
  ::Employments::Country.create!(name: "Estados Unidos")
  ::Employments::Country.create!(name: "Estonia")
  ::Employments::Country.create!(name: "Etiopía")
  ::Employments::Country.create!(name: "Filipinas")
  ::Employments::Country.create!(name: "Finlandia")
  ::Employments::Country.create!(name: "Fiyi")
  ::Employments::Country.create!(name: "Francia")
  ::Employments::Country.create!(name: "Gabón")
  ::Employments::Country.create!(name: "Gambia")
  ::Employments::Country.create!(name: "Gaza Strip")
  ::Employments::Country.create!(name: "Georgia")
  ::Employments::Country.create!(name: "Ghana")
  ::Employments::Country.create!(name: "Gibraltar")
  ::Employments::Country.create!(name: "Granada")
  ::Employments::Country.create!(name: "Grecia")
  ::Employments::Country.create!(name: "Groenlandia")
  ::Employments::Country.create!(name: "Guam")
  ::Employments::Country.create!(name: "Guatemala")
  ::Employments::Country.create!(name: "Guernsey")
  ::Employments::Country.create!(name: "Guinea")
  ::Employments::Country.create!(name: "Guinea Ecuatorial")
  ::Employments::Country.create!(name: "Guinea-Bissau")
  ::Employments::Country.create!(name: "Guyana")
  ::Employments::Country.create!(name: "Haití")
  ::Employments::Country.create!(name: "Honduras")
  ::Employments::Country.create!(name: "Hong Kong")
  ::Employments::Country.create!(name: "Hungría")
  ::Employments::Country.create!(name: "India")
  ::Employments::Country.create!(name: "Indian Ocean")
  ::Employments::Country.create!(name: "Indonesia")
  ::Employments::Country.create!(name: "Irán")
  ::Employments::Country.create!(name: "Iraq")
  ::Employments::Country.create!(name: "Irlanda")
  ::Employments::Country.create!(name: "Isla Bouvet")
  ::Employments::Country.create!(name: "Isla Christmas")
  ::Employments::Country.create!(name: "Isla Norfolk")
  ::Employments::Country.create!(name: "Islandia")
  ::Employments::Country.create!(name: "Islas Caimán")
  ::Employments::Country.create!(name: "Islas Cocos")
  ::Employments::Country.create!(name: "Islas Cook")
  ::Employments::Country.create!(name: "Islas Feroe")
  ::Employments::Country.create!(name: "Islas Georgia del Sur y Sandwich del Sur")
  ::Employments::Country.create!(name: "Islas Heard y McDonald")
  ::Employments::Country.create!(name: "Islas Malvinas")
  ::Employments::Country.create!(name: "Islas Marianas del Norte")
  ::Employments::Country.create!(name: "Islas Marshall")
  ::Employments::Country.create!(name: "Islas Pitcairn")
  ::Employments::Country.create!(name: "Islas Salomón")
  ::Employments::Country.create!(name: "Islas Turcas y Caicos")
  ::Employments::Country.create!(name: "Islas Vírgenes Americanas")
  ::Employments::Country.create!(name: "Islas Vírgenes Británicas")
  ::Employments::Country.create!(name: "Israel")
  ::Employments::Country.create!(name: "Italia")
  ::Employments::Country.create!(name: "Jamaica")
  ::Employments::Country.create!(name: "Jan Mayen")
  ::Employments::Country.create!(name: "Japón")
  ::Employments::Country.create!(name: "Jersey")
  ::Employments::Country.create!(name: "Jordania")
  ::Employments::Country.create!(name: "Kazajistán")
  ::Employments::Country.create!(name: "Kenia")
  ::Employments::Country.create!(name: "Kirguizistán")
  ::Employments::Country.create!(name: "Kiribati")
  ::Employments::Country.create!(name: "Kuwait")
  ::Employments::Country.create!(name: "Laos")
  ::Employments::Country.create!(name: "Lesoto")
  ::Employments::Country.create!(name: "Letonia")
  ::Employments::Country.create!(name: "Líbano")
  ::Employments::Country.create!(name: "Liberia")
  ::Employments::Country.create!(name: "Libia")
  ::Employments::Country.create!(name: "Liechtenstein")
  ::Employments::Country.create!(name: "Lituania")
  ::Employments::Country.create!(name: "Luxemburgo")
  ::Employments::Country.create!(name: "Macao")
  ::Employments::Country.create!(name: "Macedonia")
  ::Employments::Country.create!(name: "Madagascar")
  ::Employments::Country.create!(name: "Malasia")
  ::Employments::Country.create!(name: "Malaui")
  ::Employments::Country.create!(name: "Maldivas")
  ::Employments::Country.create!(name: "Malí")
  ::Employments::Country.create!(name: "Malta")
  ::Employments::Country.create!(name: "Man, Isle of")
  ::Employments::Country.create!(name: "Marruecos")
  ::Employments::Country.create!(name: "Mauricio")
  ::Employments::Country.create!(name: "Mauritania")
  ::Employments::Country.create!(name: "Mayotte")
  ::Employments::Country.create!(name: "México")
  ::Employments::Country.create!(name: "Micronesia")
  ::Employments::Country.create!(name: "Moldavia")
  ::Employments::Country.create!(name: "Mónaco")
  ::Employments::Country.create!(name: "Mongolia")
  ::Employments::Country.create!(name: "Montenegro")
  ::Employments::Country.create!(name: "Montserrat")
  ::Employments::Country.create!(name: "Mozambique")
  ::Employments::Country.create!(name: "Mundo")
  ::Employments::Country.create!(name: "Namibia")
  ::Employments::Country.create!(name: "Nauru")
  ::Employments::Country.create!(name: "Navassa Island")
  ::Employments::Country.create!(name: "Nepal")
  ::Employments::Country.create!(name: "Nicaragua")
  ::Employments::Country.create!(name: "Níger")
  ::Employments::Country.create!(name: "Nigeria")
  ::Employments::Country.create!(name: "Niue")
  ::Employments::Country.create!(name: "Noruega")
  ::Employments::Country.create!(name: "Nueva Caledonia")
  ::Employments::Country.create!(name: "Nueva Zelanda")
  ::Employments::Country.create!(name: "Omán")
  ::Employments::Country.create!(name: "Pacific Ocean")
  ::Employments::Country.create!(name: "Países Bajos")
  ::Employments::Country.create!(name: "Pakistán")
  ::Employments::Country.create!(name: "Palaos")
  ::Employments::Country.create!(name: "Panamá")
  ::Employments::Country.create!(name: "Papúa-Nueva Guinea")
  ::Employments::Country.create!(name: "Paracel Islands")
  ::Employments::Country.create!(name: "Paraguay")
  ::Employments::Country.create!(name: "Perú")
  ::Employments::Country.create!(name: "Polinesia Francesa")
  ::Employments::Country.create!(name: "Polonia")
  ::Employments::Country.create!(name: "Portugal")
  ::Employments::Country.create!(name: "Puerto Rico")
  ::Employments::Country.create!(name: "Qatar")
  ::Employments::Country.create!(name: "Reino Unido")
  ::Employments::Country.create!(name: "República Centroafricana")
  ::Employments::Country.create!(name: "República Checa")
  ::Employments::Country.create!(name: "República Democrática del Congo")
  ::Employments::Country.create!(name: "República Dominicana")
  ::Employments::Country.create!(name: "Ruanda")
  ::Employments::Country.create!(name: "Rumania")
  ::Employments::Country.create!(name: "Rusia")
  ::Employments::Country.create!(name: "Sáhara Occidental")
  ::Employments::Country.create!(name: "Samoa")
  ::Employments::Country.create!(name: "Samoa Americana")
  ::Employments::Country.create!(name: "San Cristóbal y Nieves")
  ::Employments::Country.create!(name: "San Marino")
  ::Employments::Country.create!(name: "San Pedro y Miquelón")
  ::Employments::Country.create!(name: "San Vicente y las Granadinas")
  ::Employments::Country.create!(name: "Santa Helena")
  ::Employments::Country.create!(name: "Santa Lucía")
  ::Employments::Country.create!(name: "Santo Tomé y Príncipe")
  ::Employments::Country.create!(name: "Senegal")
  ::Employments::Country.create!(name: "Serbia")
  ::Employments::Country.create!(name: "Seychelles")
  ::Employments::Country.create!(name: "Sierra Leona")
  ::Employments::Country.create!(name: "Singapur")
  ::Employments::Country.create!(name: "Siria")
  ::Employments::Country.create!(name: "Somalia")
  ::Employments::Country.create!(name: "Southern Ocean")
  ::Employments::Country.create!(name: "Spratly Islands")
  ::Employments::Country.create!(name: "Sri Lanka")
  ::Employments::Country.create!(name: "Suazilandia")
  ::Employments::Country.create!(name: "Sudáfrica")
  ::Employments::Country.create!(name: "Sudán")
  ::Employments::Country.create!(name: "Suecia")
  ::Employments::Country.create!(name: "Suiza")
  ::Employments::Country.create!(name: "Surinam")
  ::Employments::Country.create!(name: "Svalbard y Jan Mayen")
  ::Employments::Country.create!(name: "Tailandia")
  ::Employments::Country.create!(name: "Taiwán")
  ::Employments::Country.create!(name: "Tanzania")
  ::Employments::Country.create!(name: "Tayikistán")
  ::Employments::Country.create!(name: "Territorio Británico del Océano Indico")
  ::Employments::Country.create!(name: "Territorios Australes Franceses")
  ::Employments::Country.create!(name: "Timor Oriental")
  ::Employments::Country.create!(name: "Togo")
  ::Employments::Country.create!(name: "Tokelau")
  ::Employments::Country.create!(name: "Tonga")
  ::Employments::Country.create!(name: "Trinidad y Tobago")
  ::Employments::Country.create!(name: "Túnez")
  ::Employments::Country.create!(name: "Turkmenistán")
  ::Employments::Country.create!(name: "Turquía")
  ::Employments::Country.create!(name: "Tuvalu")
  ::Employments::Country.create!(name: "Ucrania")
  ::Employments::Country.create!(name: "Uganda")
  ::Employments::Country.create!(name: "Unión Europea")
  ::Employments::Country.create!(name: "Uruguay")
  ::Employments::Country.create!(name: "Uzbekistán")
  ::Employments::Country.create!(name: "Vanuatu")
  ::Employments::Country.create!(name: "Venezuela")
  ::Employments::Country.create!(name: "Vietnam")
  ::Employments::Country.create!(name: "Wake Island")
  ::Employments::Country.create!(name: "Wallis y Futuna")
  ::Employments::Country.create!(name: "West Bank")
  ::Employments::Country.create!(name: "Yemen")
  ::Employments::Country.create!(name: "Yibuti")
  ::Employments::Country.create!(name: "Zambia")
  ::Employments::Country.create!(name: "Zimbabue")
end
