require 'net/http'
require 'json'

namespace :employments do

  desc 'Load default data'
  task :default_data => [:environment] do
    # Load countries table
    ::Employments::Country.destroy_all
    ::Employments::Country.where(id:1).first_or_create(name: 'Afganistán')
    ::Employments::Country.where(id:2).first_or_create(name: 'Akrotiri')
    ::Employments::Country.where(id:3).first_or_create(name: 'Albania')
    ::Employments::Country.where(id:4).first_or_create(name: 'Alemania')
    ::Employments::Country.where(id:5).first_or_create(name: 'Andorra')
    ::Employments::Country.where(id:6).first_or_create(name: 'Angola')
    ::Employments::Country.where(id:7).first_or_create(name: 'Anguila')
    ::Employments::Country.where(id:8).first_or_create(name: 'Antártida')
    ::Employments::Country.where(id:9).first_or_create(name: 'Antigua y Barbuda')
    ::Employments::Country.where(id:10).first_or_create(name: 'Antillas Neerlandesas')
    ::Employments::Country.where(id:11).first_or_create(name: 'Arabia Saudí')
    ::Employments::Country.where(id:12).first_or_create(name: 'Arctic Ocean')
    ::Employments::Country.where(id:13).first_or_create(name: 'Argelia')
    ::Employments::Country.where(id:14).first_or_create(name: 'Argentina')
    ::Employments::Country.where(id:15).first_or_create(name: 'Armenia')
    ::Employments::Country.where(id:16).first_or_create(name: 'Aruba')
    ::Employments::Country.where(id:17).first_or_create(name: 'Ashmore and Cartier Islands')
    ::Employments::Country.where(id:18).first_or_create(name: 'Atlantic Ocean')
    ::Employments::Country.where(id:19).first_or_create(name: 'Australia')
    ::Employments::Country.where(id:20).first_or_create(name: 'Austria')
    ::Employments::Country.where(id:21).first_or_create(name: 'Azerbaiyán')
    ::Employments::Country.where(id:22).first_or_create(name: 'Bahamas')
    ::Employments::Country.where(id:23).first_or_create(name: 'Bahráin')
    ::Employments::Country.where(id:24).first_or_create(name: 'Bangladesh')
    ::Employments::Country.where(id:25).first_or_create(name: 'Barbados')
    ::Employments::Country.where(id:26).first_or_create(name: 'Bélgica')
    ::Employments::Country.where(id:27).first_or_create(name: 'Belice')
    ::Employments::Country.where(id:28).first_or_create(name: 'Benín')
    ::Employments::Country.where(id:29).first_or_create(name: 'Bermudas')
    ::Employments::Country.where(id:30).first_or_create(name: 'Bielorrusia')
    ::Employments::Country.where(id:31).first_or_create(name: 'Birmania; Myanmar')
    ::Employments::Country.where(id:32).first_or_create(name: 'Bolivia')
    ::Employments::Country.where(id:33).first_or_create(name: 'Bosnia y Hercegovina')
    ::Employments::Country.where(id:34).first_or_create(name: 'Botsuana')
    ::Employments::Country.where(id:35).first_or_create(name: 'Brasil')
    ::Employments::Country.where(id:36).first_or_create(name: 'Brunéi')
    ::Employments::Country.where(id:37).first_or_create(name: 'Bulgaria')
    ::Employments::Country.where(id:38).first_or_create(name: 'Burkina Faso')
    ::Employments::Country.where(id:39).first_or_create(name: 'Burundi')
    ::Employments::Country.where(id:40).first_or_create(name: 'Bután')
    ::Employments::Country.where(id:41).first_or_create(name: 'Cabo Verde')
    ::Employments::Country.where(id:42).first_or_create(name: 'Camboya')
    ::Employments::Country.where(id:43).first_or_create(name: 'Camerún')
    ::Employments::Country.where(id:44).first_or_create(name: 'Canadá')
    ::Employments::Country.where(id:45).first_or_create(name: 'Chad')
    ::Employments::Country.where(id:46).first_or_create(name: 'Chile')
    ::Employments::Country.where(id:47).first_or_create(name: 'China')
    ::Employments::Country.where(id:48).first_or_create(name: 'Chipre')
    ::Employments::Country.where(id:49).first_or_create(name: 'Clipperton Island')
    ::Employments::Country.where(id:50).first_or_create(name: 'Colombia')
    ::Employments::Country.where(id:51).first_or_create(name: 'Comoras')
    ::Employments::Country.where(id:52).first_or_create(name: 'Congo')
    ::Employments::Country.where(id:53).first_or_create(name: 'Coral Sea Islands')
    ::Employments::Country.where(id:54).first_or_create(name: 'Corea del Norte')
    ::Employments::Country.where(id:55).first_or_create(name: 'Corea del Sur')
    ::Employments::Country.where(id:56).first_or_create(name: 'Costa de Marfil')
    ::Employments::Country.where(id:57).first_or_create(name: 'Costa Rica')
    ::Employments::Country.where(id:58).first_or_create(name: 'Croacia')
    ::Employments::Country.where(id:59).first_or_create(name: 'Cuba')
    ::Employments::Country.where(id:60).first_or_create(name: 'Dhekelia')
    ::Employments::Country.where(id:61).first_or_create(name: 'Dinamarca')
    ::Employments::Country.where(id:62).first_or_create(name: 'Dominica')
    ::Employments::Country.where(id:63).first_or_create(name: 'Ecuador')
    ::Employments::Country.where(id:64).first_or_create(name: 'Egipto')
    ::Employments::Country.where(id:65).first_or_create(name: 'El Salvador')
    ::Employments::Country.where(id:66).first_or_create(name: 'El Vaticano')
    ::Employments::Country.where(id:67).first_or_create(name: 'Emiratos Árabes Unidos')
    ::Employments::Country.where(id:68).first_or_create(name: 'Eritrea')
    ::Employments::Country.where(id:69).first_or_create(name: 'Eslovaquia')
    ::Employments::Country.where(id:70).first_or_create(name: 'Eslovenia')
    ::Employments::Country.where(id:71).first_or_create(name: 'España')
    ::Employments::Country.where(id:72).first_or_create(name: 'Estados Unidos')
    ::Employments::Country.where(id:73).first_or_create(name: 'Estonia')
    ::Employments::Country.where(id:74).first_or_create(name: 'Etiopía')
    ::Employments::Country.where(id:75).first_or_create(name: 'Filipinas')
    ::Employments::Country.where(id:76).first_or_create(name: 'Finlandia')
    ::Employments::Country.where(id:77).first_or_create(name: 'Fiyi')
    ::Employments::Country.where(id:78).first_or_create(name: 'Francia')
    ::Employments::Country.where(id:79).first_or_create(name: 'Gabón')
    ::Employments::Country.where(id:80).first_or_create(name: 'Gambia')
    ::Employments::Country.where(id:81).first_or_create(name: 'Gaza Strip')
    ::Employments::Country.where(id:82).first_or_create(name: 'Georgia')
    ::Employments::Country.where(id:83).first_or_create(name: 'Ghana')
    ::Employments::Country.where(id:84).first_or_create(name: 'Gibraltar')
    ::Employments::Country.where(id:85).first_or_create(name: 'Granada')
    ::Employments::Country.where(id:86).first_or_create(name: 'Grecia')
    ::Employments::Country.where(id:87).first_or_create(name: 'Groenlandia')
    ::Employments::Country.where(id:88).first_or_create(name: 'Guam')
    ::Employments::Country.where(id:89).first_or_create(name: 'Guatemala')
    ::Employments::Country.where(id:90).first_or_create(name: 'Guernsey')
    ::Employments::Country.where(id:91).first_or_create(name: 'Guinea')
    ::Employments::Country.where(id:92).first_or_create(name: 'Guinea Ecuatorial')
    ::Employments::Country.where(id:93).first_or_create(name: 'Guinea-Bissau')
    ::Employments::Country.where(id:94).first_or_create(name: 'Guyana')
    ::Employments::Country.where(id:95).first_or_create(name: 'Haití')
    ::Employments::Country.where(id:96).first_or_create(name: 'Honduras')
    ::Employments::Country.where(id:97).first_or_create(name: 'Hong Kong')
    ::Employments::Country.where(id:98).first_or_create(name: 'Hungría')
    ::Employments::Country.where(id:99).first_or_create(name: 'India')
    ::Employments::Country.where(id:100).first_or_create(name: 'Indian Ocean')
    ::Employments::Country.where(id:101).first_or_create(name: 'Indonesia')
    ::Employments::Country.where(id:102).first_or_create(name: 'Irán')
    ::Employments::Country.where(id:103).first_or_create(name: 'Iraq')
    ::Employments::Country.where(id:104).first_or_create(name: 'Irlanda')
    ::Employments::Country.where(id:105).first_or_create(name: 'Isla Bouvet')
    ::Employments::Country.where(id:106).first_or_create(name: 'Isla Christmas')
    ::Employments::Country.where(id:107).first_or_create(name: 'Isla Norfolk')
    ::Employments::Country.where(id:108).first_or_create(name: 'Islandia')
    ::Employments::Country.where(id:109).first_or_create(name: 'Islas Caimán')
    ::Employments::Country.where(id:110).first_or_create(name: 'Islas Cocos')
    ::Employments::Country.where(id:111).first_or_create(name: 'Islas Cook')
    ::Employments::Country.where(id:112).first_or_create(name: 'Islas Feroe')
    ::Employments::Country.where(id:113).first_or_create(name: 'Islas Georgia del Sur y Sandwich del Sur')
    ::Employments::Country.where(id:114).first_or_create(name: 'Islas Heard y McDonald')
    ::Employments::Country.where(id:115).first_or_create(name: 'Islas Malvinas')
    ::Employments::Country.where(id:116).first_or_create(name: 'Islas Marianas del Norte')
    ::Employments::Country.where(id:117).first_or_create(name: 'Islas Marshall')
    ::Employments::Country.where(id:118).first_or_create(name: 'Islas Pitcairn')
    ::Employments::Country.where(id:119).first_or_create(name: 'Islas Salomón')
    ::Employments::Country.where(id:120).first_or_create(name: 'Islas Turcas y Caicos')
    ::Employments::Country.where(id:121).first_or_create(name: 'Islas Vírgenes Americanas')
    ::Employments::Country.where(id:122).first_or_create(name: 'Islas Vírgenes Británicas')
    ::Employments::Country.where(id:123).first_or_create(name: 'Israel')
    ::Employments::Country.where(id:124).first_or_create(name: 'Italia')
    ::Employments::Country.where(id:125).first_or_create(name: 'Jamaica')
    ::Employments::Country.where(id:126).first_or_create(name: 'Jan Mayen')
    ::Employments::Country.where(id:127).first_or_create(name: 'Japón')
    ::Employments::Country.where(id:128).first_or_create(name: 'Jersey')
    ::Employments::Country.where(id:129).first_or_create(name: 'Jordania')
    ::Employments::Country.where(id:130).first_or_create(name: 'Kazajistán')
    ::Employments::Country.where(id:131).first_or_create(name: 'Kenia')
    ::Employments::Country.where(id:132).first_or_create(name: 'Kirguizistán')
    ::Employments::Country.where(id:133).first_or_create(name: 'Kiribati')
    ::Employments::Country.where(id:134).first_or_create(name: 'Kuwait')
    ::Employments::Country.where(id:135).first_or_create(name: 'Laos')
    ::Employments::Country.where(id:136).first_or_create(name: 'Lesoto')
    ::Employments::Country.where(id:137).first_or_create(name: 'Letonia')
    ::Employments::Country.where(id:138).first_or_create(name: 'Líbano')
    ::Employments::Country.where(id:139).first_or_create(name: 'Liberia')
    ::Employments::Country.where(id:140).first_or_create(name: 'Libia')
    ::Employments::Country.where(id:141).first_or_create(name: 'Liechtenstein')
    ::Employments::Country.where(id:142).first_or_create(name: 'Lituania')
    ::Employments::Country.where(id:143).first_or_create(name: 'Luxemburgo')
    ::Employments::Country.where(id:144).first_or_create(name: 'Macao')
    ::Employments::Country.where(id:145).first_or_create(name: 'Macedonia')
    ::Employments::Country.where(id:146).first_or_create(name: 'Madagascar')
    ::Employments::Country.where(id:147).first_or_create(name: 'Malasia')
    ::Employments::Country.where(id:148).first_or_create(name: 'Malaui')
    ::Employments::Country.where(id:149).first_or_create(name: 'Maldivas')
    ::Employments::Country.where(id:150).first_or_create(name: 'Malí')
    ::Employments::Country.where(id:151).first_or_create(name: 'Malta')
    ::Employments::Country.where(id:152).first_or_create(name: 'Man, Isle of')
    ::Employments::Country.where(id:153).first_or_create(name: 'Marruecos')
    ::Employments::Country.where(id:154).first_or_create(name: 'Mauricio')
    ::Employments::Country.where(id:155).first_or_create(name: 'Mauritania')
    ::Employments::Country.where(id:156).first_or_create(name: 'Mayotte')
    ::Employments::Country.where(id:157).first_or_create(name: 'México')
    ::Employments::Country.where(id:158).first_or_create(name: 'Micronesia')
    ::Employments::Country.where(id:159).first_or_create(name: 'Moldavia')
    ::Employments::Country.where(id:160).first_or_create(name: 'Mónaco')
    ::Employments::Country.where(id:161).first_or_create(name: 'Mongolia')
    ::Employments::Country.where(id:162).first_or_create(name: 'Montenegro')
    ::Employments::Country.where(id:163).first_or_create(name: 'Montserrat')
    ::Employments::Country.where(id:164).first_or_create(name: 'Mozambique')
    ::Employments::Country.where(id:165).first_or_create(name: 'Mundo')
    ::Employments::Country.where(id:166).first_or_create(name: 'Namibia')
    ::Employments::Country.where(id:167).first_or_create(name: 'Nauru')
    ::Employments::Country.where(id:168).first_or_create(name: 'Navassa Island')
    ::Employments::Country.where(id:169).first_or_create(name: 'Nepal')
    ::Employments::Country.where(id:170).first_or_create(name: 'Nicaragua')
    ::Employments::Country.where(id:171).first_or_create(name: 'Níger')
    ::Employments::Country.where(id:172).first_or_create(name: 'Nigeria')
    ::Employments::Country.where(id:173).first_or_create(name: 'Niue')
    ::Employments::Country.where(id:174).first_or_create(name: 'Noruega')
    ::Employments::Country.where(id:175).first_or_create(name: 'Nueva Caledonia')
    ::Employments::Country.where(id:176).first_or_create(name: 'Nueva Zelanda')
    ::Employments::Country.where(id:177).first_or_create(name: 'Omán')
    ::Employments::Country.where(id:178).first_or_create(name: 'Pacific Ocean')
    ::Employments::Country.where(id:179).first_or_create(name: 'Países Bajos')
    ::Employments::Country.where(id:180).first_or_create(name: 'Pakistán')
    ::Employments::Country.where(id:181).first_or_create(name: 'Palaos')
    ::Employments::Country.where(id:182).first_or_create(name: 'Panamá')
    ::Employments::Country.where(id:183).first_or_create(name: 'Papúa-Nueva Guinea')
    ::Employments::Country.where(id:184).first_or_create(name: 'Paracel Islands')
    ::Employments::Country.where(id:185).first_or_create(name: 'Paraguay')
    ::Employments::Country.where(id:186).first_or_create(name: 'Perú')
    ::Employments::Country.where(id:187).first_or_create(name: 'Polinesia Francesa')
    ::Employments::Country.where(id:188).first_or_create(name: 'Polonia')
    ::Employments::Country.where(id:189).first_or_create(name: 'Portugal')
    ::Employments::Country.where(id:190).first_or_create(name: 'Puerto Rico')
    ::Employments::Country.where(id:191).first_or_create(name: 'Qatar')
    ::Employments::Country.where(id:192).first_or_create(name: 'Reino Unido')
    ::Employments::Country.where(id:193).first_or_create(name: 'República Centroafricana')
    ::Employments::Country.where(id:194).first_or_create(name: 'República Checa')
    ::Employments::Country.where(id:195).first_or_create(name: 'República Democrática del Congo')
    ::Employments::Country.where(id:196).first_or_create(name: 'República Dominicana')
    ::Employments::Country.where(id:197).first_or_create(name: 'Ruanda')
    ::Employments::Country.where(id:198).first_or_create(name: 'Rumania')
    ::Employments::Country.where(id:199).first_or_create(name: 'Rusia')
    ::Employments::Country.where(id:200).first_or_create(name: 'Sáhara Occidental')
    ::Employments::Country.where(id:201).first_or_create(name: 'Samoa')
    ::Employments::Country.where(id:202).first_or_create(name: 'Samoa Americana')
    ::Employments::Country.where(id:203).first_or_create(name: 'San Cristóbal y Nieves')
    ::Employments::Country.where(id:204).first_or_create(name: 'San Marino')
    ::Employments::Country.where(id:205).first_or_create(name: 'San Pedro y Miquelón')
    ::Employments::Country.where(id:206).first_or_create(name: 'San Vicente y las Granadinas')
    ::Employments::Country.where(id:207).first_or_create(name: 'Santa Helena')
    ::Employments::Country.where(id:208).first_or_create(name: 'Santa Lucía')
    ::Employments::Country.where(id:209).first_or_create(name: 'Santo Tomé y Príncipe')
    ::Employments::Country.where(id:210).first_or_create(name: 'Senegal')
    ::Employments::Country.where(id:211).first_or_create(name: 'Serbia')
    ::Employments::Country.where(id:212).first_or_create(name: 'Seychelles')
    ::Employments::Country.where(id:213).first_or_create(name: 'Sierra Leona')
    ::Employments::Country.where(id:214).first_or_create(name: 'Singapur')
    ::Employments::Country.where(id:215).first_or_create(name: 'Siria')
    ::Employments::Country.where(id:216).first_or_create(name: 'Somalia')
    ::Employments::Country.where(id:217).first_or_create(name: 'Southern Ocean')
    ::Employments::Country.where(id:218).first_or_create(name: 'Spratly Islands')
    ::Employments::Country.where(id:219).first_or_create(name: 'Sri Lanka')
    ::Employments::Country.where(id:220).first_or_create(name: 'Suazilandia')
    ::Employments::Country.where(id:221).first_or_create(name: 'Sudáfrica')
    ::Employments::Country.where(id:222).first_or_create(name: 'Sudán')
    ::Employments::Country.where(id:223).first_or_create(name: 'Suecia')
    ::Employments::Country.where(id:224).first_or_create(name: 'Suiza')
    ::Employments::Country.where(id:225).first_or_create(name: 'Surinam')
    ::Employments::Country.where(id:226).first_or_create(name: 'Svalbard y Jan Mayen')
    ::Employments::Country.where(id:227).first_or_create(name: 'Tailandia')
    ::Employments::Country.where(id:228).first_or_create(name: 'Taiwán')
    ::Employments::Country.where(id:229).first_or_create(name: 'Tanzania')
    ::Employments::Country.where(id:230).first_or_create(name: 'Tayikistán')
    ::Employments::Country.where(id:231).first_or_create(name: 'Territorio Británico del Océano Indico')
    ::Employments::Country.where(id:232).first_or_create(name: 'Territorios Australes Franceses')
    ::Employments::Country.where(id:233).first_or_create(name: 'Timor Oriental')
    ::Employments::Country.where(id:234).first_or_create(name: 'Togo')
    ::Employments::Country.where(id:235).first_or_create(name: 'Tokelau')
    ::Employments::Country.where(id:236).first_or_create(name: 'Tonga')
    ::Employments::Country.where(id:237).first_or_create(name: 'Trinidad y Tobago')
    ::Employments::Country.where(id:238).first_or_create(name: 'Túnez')
    ::Employments::Country.where(id:239).first_or_create(name: 'Turkmenistán')
    ::Employments::Country.where(id:240).first_or_create(name: 'Turquía')
    ::Employments::Country.where(id:241).first_or_create(name: 'Tuvalu')
    ::Employments::Country.where(id:242).first_or_create(name: 'Ucrania')
    ::Employments::Country.where(id:243).first_or_create(name: 'Uganda')
    ::Employments::Country.where(id:244).first_or_create(name: 'Unión Europea')
    ::Employments::Country.where(id:245).first_or_create(name: 'Uruguay')
    ::Employments::Country.where(id:246).first_or_create(name: 'Uzbekistán')
    ::Employments::Country.where(id:247).first_or_create(name: 'Vanuatu')
    ::Employments::Country.where(id:248).first_or_create(name: 'Venezuela')
    ::Employments::Country.where(id:249).first_or_create(name: 'Vietnam')
    ::Employments::Country.where(id:250).first_or_create(name: 'Wake Island')
    ::Employments::Country.where(id:251).first_or_create(name: 'Wallis y Futuna')
    ::Employments::Country.where(id:252).first_or_create(name: 'West Bank')
    ::Employments::Country.where(id:253).first_or_create(name: 'Yemen')
    ::Employments::Country.where(id:254).first_or_create(name: 'Yibuti')
    ::Employments::Country.where(id:255).first_or_create(name: 'Zambia')
    ::Employments::Country.where(id:256).first_or_create(name: 'Zimbabue')

    # Load Disability Type table
    ::Employments::DisabilityType.destroy_all
    ::Employments::DisabilityType.where(id: 1).first_or_create(name: "Física: miembros inferiores, miembros superiores")
    ::Employments::DisabilityType.where(id: 2).first_or_create(name: "Mental")
    ::Employments::DisabilityType.where(id: 3).first_or_create(name: "Intelectuales")
    ::Employments::DisabilityType.where(id: 4).first_or_create(name: "Visual: baja visión, ceguera total")
    ::Employments::DisabilityType.where(id: 5).first_or_create(name: "Audición: hipoacusia, sordera total, deficiencia auditiva")

    # Load Disability Certification table
    ::Employments::DisabilityCertification.destroy_all
    ::Employments::DisabilityCertification.where(id: 1).first_or_create(name: "ISSS")
    ::Employments::DisabilityCertification.where(id: 2).first_or_create(name: "ISRI")
    ::Employments::DisabilityCertification.where(id: 3).first_or_create(name: "FOPROLYD")
    ::Employments::DisabilityCertification.where(id: 4).first_or_create(name: "IPSFA")
    ::Employments::DisabilityCertification.where(id: 5).first_or_create(name: "INPEP")
    ::Employments::DisabilityCertification.where(id: 6).first_or_create(name: "ISRI")
    ::Employments::DisabilityCertification.where(id: 7).first_or_create(name: "SSF")
    ::Employments::DisabilityCertification.where(id: 8).first_or_create(name: "[no poseo certificación]")

  end

  desc 'Confirm all users'
  task :confirm_users => [:environment] do
    User.all.each{|u| u.update_column(:confirmed_at, u.created_at)}
  end

end
